# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server.openapi import util


class CreateQueueResponse(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, queue_id=None):  # noqa: E501
        """CreateQueueResponse - a model defined in OpenAPI

        :param queue_id: The queue_id of this CreateQueueResponse.  # noqa: E501
        :type queue_id: str
        """
        self.openapi_types = {
            'queue_id': str
        }

        self.attribute_map = {
            'queue_id': 'queueId'
        }

        self._queue_id = queue_id

    @classmethod
    def from_dict(cls, dikt) -> 'CreateQueueResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The CreateQueueResponse of this CreateQueueResponse.  # noqa: E501
        :rtype: CreateQueueResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def queue_id(self):
        """Gets the queue_id of this CreateQueueResponse.

        Queue ID  # noqa: E501

        :return: The queue_id of this CreateQueueResponse.
        :rtype: str
        """
        return self._queue_id

    @queue_id.setter
    def queue_id(self, queue_id):
        """Sets the queue_id of this CreateQueueResponse.

        Queue ID  # noqa: E501

        :param queue_id: The queue_id of this CreateQueueResponse.
        :type queue_id: str
        """

        self._queue_id = queue_id
