# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class CreateSubmissionResponse(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, submission_id=None):  # noqa: E501
        """CreateSubmissionResponse - a model defined in OpenAPI

        :param submission_id: The submission_id of this CreateSubmissionResponse.  # noqa: E501
        :type submission_id: str
        """
        self.openapi_types = {
            'submission_id': str
        }

        self.attribute_map = {
            'submission_id': 'submissionId'
        }

        self._submission_id = submission_id

    @classmethod
    def from_dict(cls, dikt) -> 'CreateSubmissionResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The CreateSubmissionResponse of this CreateSubmissionResponse.  # noqa: E501
        :rtype: CreateSubmissionResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def submission_id(self):
        """Gets the submission_id of this CreateSubmissionResponse.

        Submission ID  # noqa: E501

        :return: The submission_id of this CreateSubmissionResponse.
        :rtype: str
        """
        return self._submission_id

    @submission_id.setter
    def submission_id(self, submission_id):
        """Sets the submission_id of this CreateSubmissionResponse.

        Submission ID  # noqa: E501

        :param submission_id: The submission_id of this CreateSubmissionResponse.
        :type submission_id: str
        """

        self._submission_id = submission_id
