# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server.openapi import util


class CreateComputeEnvResponse(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, compute_env_id=None):  # noqa: E501
        """CreateComputeEnvResponse - a model defined in OpenAPI

        :param compute_env_id: The compute_env_id of this CreateComputeEnvResponse.  # noqa: E501
        :type compute_env_id: str
        """
        self.openapi_types = {
            'compute_env_id': str
        }

        self.attribute_map = {
            'compute_env_id': 'computeEnvId'
        }

        self._compute_env_id = compute_env_id

    @classmethod
    def from_dict(cls, dikt) -> 'CreateComputeEnvResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The CreateComputeEnvResponse of this CreateComputeEnvResponse.  # noqa: E501
        :rtype: CreateComputeEnvResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def compute_env_id(self):
        """Gets the compute_env_id of this CreateComputeEnvResponse.

        Compute environment ID  # noqa: E501

        :return: The compute_env_id of this CreateComputeEnvResponse.
        :rtype: str
        """
        return self._compute_env_id

    @compute_env_id.setter
    def compute_env_id(self, compute_env_id):
        """Sets the compute_env_id of this CreateComputeEnvResponse.

        Compute environment ID  # noqa: E501

        :param compute_env_id: The compute_env_id of this CreateComputeEnvResponse.
        :type compute_env_id: str
        """

        self._compute_env_id = compute_env_id
