# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class CreateTeamRequest(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, team_id=None, name=None, description=None):  # noqa: E501
        """CreateTeamRequest - a model defined in OpenAPI

        :param team_id: The team_id of this CreateTeamRequest.  # noqa: E501
        :type team_id: str
        :param name: The name of this CreateTeamRequest.  # noqa: E501
        :type name: str
        :param description: The description of this CreateTeamRequest.  # noqa: E501
        :type description: str
        """
        self.openapi_types = {
            'team_id': str,
            'name': str,
            'description': str
        }

        self.attribute_map = {
            'team_id': 'teamId',
            'name': 'name',
            'description': 'description'
        }

        self._team_id = team_id
        self._name = name
        self._description = description

    @classmethod
    def from_dict(cls, dikt) -> 'CreateTeamRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The CreateTeamRequest of this CreateTeamRequest.  # noqa: E501
        :rtype: CreateTeamRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def team_id(self):
        """Gets the team_id of this CreateTeamRequest.

        ID of team.  # noqa: E501

        :return: The team_id of this CreateTeamRequest.
        :rtype: str
        """
        return self._team_id

    @team_id.setter
    def team_id(self, team_id):
        """Sets the team_id of this CreateTeamRequest.

        ID of team.  # noqa: E501

        :param team_id: The team_id of this CreateTeamRequest.
        :type team_id: str
        """

        self._team_id = team_id

    @property
    def name(self):
        """Gets the name of this CreateTeamRequest.

        Name of team.  # noqa: E501

        :return: The name of this CreateTeamRequest.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this CreateTeamRequest.

        Name of team.  # noqa: E501

        :param name: The name of this CreateTeamRequest.
        :type name: str
        """

        self._name = name

    @property
    def description(self):
        """Gets the description of this CreateTeamRequest.

        Description of Team.  # noqa: E501

        :return: The description of this CreateTeamRequest.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this CreateTeamRequest.

        Description of Team.  # noqa: E501

        :param description: The description of this CreateTeamRequest.
        :type description: str
        """

        self._description = description
