# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server.models.submission_status import SubmissionStatus
from openapi_server import util

from openapi_server.models.submission_status import SubmissionStatus  # noqa: E501

class CreateFileSubmissionRequest(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, name=None, submitter=None, status=None, file=None):  # noqa: E501
        """CreateFileSubmissionRequest - a model defined in OpenAPI

        :param name: The name of this CreateFileSubmissionRequest.  # noqa: E501
        :type name: str
        :param submitter: The submitter of this CreateFileSubmissionRequest.  # noqa: E501
        :type submitter: str
        :param status: The status of this CreateFileSubmissionRequest.  # noqa: E501
        :type status: SubmissionStatus
        :param file: The file of this CreateFileSubmissionRequest.  # noqa: E501
        :type file: str
        """
        self.openapi_types = {
            'name': str,
            'submitter': str,
            'status': SubmissionStatus,
            'file': str
        }

        self.attribute_map = {
            'name': 'name',
            'submitter': 'submitter',
            'status': 'status',
            'file': 'file'
        }

        self._name = name
        self._submitter = submitter
        self._status = status
        self._file = file

    @classmethod
    def from_dict(cls, dikt) -> 'CreateFileSubmissionRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The CreateFileSubmissionRequest of this CreateFileSubmissionRequest.  # noqa: E501
        :rtype: CreateFileSubmissionRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self):
        """Gets the name of this CreateFileSubmissionRequest.

        Name of submission  # noqa: E501

        :return: The name of this CreateFileSubmissionRequest.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this CreateFileSubmissionRequest.

        Name of submission  # noqa: E501

        :param name: The name of this CreateFileSubmissionRequest.
        :type name: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def submitter(self):
        """Gets the submitter of this CreateFileSubmissionRequest.

        Submitter name  # noqa: E501

        :return: The submitter of this CreateFileSubmissionRequest.
        :rtype: str
        """
        return self._submitter

    @submitter.setter
    def submitter(self, submitter):
        """Sets the submitter of this CreateFileSubmissionRequest.

        Submitter name  # noqa: E501

        :param submitter: The submitter of this CreateFileSubmissionRequest.
        :type submitter: str
        """
        if submitter is None:
            raise ValueError("Invalid value for `submitter`, must not be `None`")  # noqa: E501

        self._submitter = submitter

    @property
    def status(self):
        """Gets the status of this CreateFileSubmissionRequest.


        :return: The status of this CreateFileSubmissionRequest.
        :rtype: SubmissionStatus
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this CreateFileSubmissionRequest.


        :param status: The status of this CreateFileSubmissionRequest.
        :type status: SubmissionStatus
        """

        self._status = status

    @property
    def file(self):
        """Gets the file of this CreateFileSubmissionRequest.

        File to submit to challenge  # noqa: E501

        :return: The file of this CreateFileSubmissionRequest.
        :rtype: str
        """
        return self._file

    @file.setter
    def file(self, file):
        """Sets the file of this CreateFileSubmissionRequest.

        File to submit to challenge  # noqa: E501

        :param file: The file of this CreateFileSubmissionRequest.
        :type file: str
        """
        if file is None:
            raise ValueError("Invalid value for `file`, must not be `None`")  # noqa: E501

        self._file = file
