# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server.openapi import util


class CreateRunRequest(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, data=None, data_version=None):  # noqa: E501
        """CreateRunRequest - a model defined in OpenAPI

        :param data: The data of this CreateRunRequest.  # noqa: E501
        :type data: str
        :param data_version: The data_version of this CreateRunRequest.  # noqa: E501
        :type data_version: str
        """
        self.openapi_types = {
            'data': str,
            'data_version': str
        }

        self.attribute_map = {
            'data': 'data',
            'data_version': 'dataVersion'
        }

        self._data = data
        self._data_version = data_version

    @classmethod
    def from_dict(cls, dikt) -> 'CreateRunRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The CreateRunRequest of this CreateRunRequest.  # noqa: E501
        :rtype: CreateRunRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def data(self):
        """Gets the data of this CreateRunRequest.

        Data location  # noqa: E501

        :return: The data of this CreateRunRequest.
        :rtype: str
        """
        return self._data

    @data.setter
    def data(self, data):
        """Sets the data of this CreateRunRequest.

        Data location  # noqa: E501

        :param data: The data of this CreateRunRequest.
        :type data: str
        """

        self._data = data

    @property
    def data_version(self):
        """Gets the data_version of this CreateRunRequest.

        Data version  # noqa: E501

        :return: The data_version of this CreateRunRequest.
        :rtype: str
        """
        return self._data_version

    @data_version.setter
    def data_version(self, data_version):
        """Sets the data_version of this CreateRunRequest.

        Data version  # noqa: E501

        :param data_version: The data_version of this CreateRunRequest.
        :type data_version: str
        """

        self._data_version = data_version
