# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server.models.docker_submission_docker import DockerSubmissionDocker
from openapi_server.models.submission_status import SubmissionStatus
from openapi_server import util

from openapi_server.models.docker_submission_docker import DockerSubmissionDocker  # noqa: E501
from openapi_server.models.submission_status import SubmissionStatus  # noqa: E501

class CreateDockerSubmissionRequest(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, name=None, submitter=None, status=None, docker=None):  # noqa: E501
        """CreateDockerSubmissionRequest - a model defined in OpenAPI

        :param name: The name of this CreateDockerSubmissionRequest.  # noqa: E501
        :type name: str
        :param submitter: The submitter of this CreateDockerSubmissionRequest.  # noqa: E501
        :type submitter: str
        :param status: The status of this CreateDockerSubmissionRequest.  # noqa: E501
        :type status: SubmissionStatus
        :param docker: The docker of this CreateDockerSubmissionRequest.  # noqa: E501
        :type docker: DockerSubmissionDocker
        """
        self.openapi_types = {
            'name': str,
            'submitter': str,
            'status': SubmissionStatus,
            'docker': DockerSubmissionDocker
        }

        self.attribute_map = {
            'name': 'name',
            'submitter': 'submitter',
            'status': 'status',
            'docker': 'docker'
        }

        self._name = name
        self._submitter = submitter
        self._status = status
        self._docker = docker

    @classmethod
    def from_dict(cls, dikt) -> 'CreateDockerSubmissionRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The CreateDockerSubmissionRequest of this CreateDockerSubmissionRequest.  # noqa: E501
        :rtype: CreateDockerSubmissionRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self):
        """Gets the name of this CreateDockerSubmissionRequest.

        Name of submission  # noqa: E501

        :return: The name of this CreateDockerSubmissionRequest.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this CreateDockerSubmissionRequest.

        Name of submission  # noqa: E501

        :param name: The name of this CreateDockerSubmissionRequest.
        :type name: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def submitter(self):
        """Gets the submitter of this CreateDockerSubmissionRequest.

        Submitter name  # noqa: E501

        :return: The submitter of this CreateDockerSubmissionRequest.
        :rtype: str
        """
        return self._submitter

    @submitter.setter
    def submitter(self, submitter):
        """Sets the submitter of this CreateDockerSubmissionRequest.

        Submitter name  # noqa: E501

        :param submitter: The submitter of this CreateDockerSubmissionRequest.
        :type submitter: str
        """
        if submitter is None:
            raise ValueError("Invalid value for `submitter`, must not be `None`")  # noqa: E501

        self._submitter = submitter

    @property
    def status(self):
        """Gets the status of this CreateDockerSubmissionRequest.


        :return: The status of this CreateDockerSubmissionRequest.
        :rtype: SubmissionStatus
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this CreateDockerSubmissionRequest.


        :param status: The status of this CreateDockerSubmissionRequest.
        :type status: SubmissionStatus
        """

        self._status = status

    @property
    def docker(self):
        """Gets the docker of this CreateDockerSubmissionRequest.


        :return: The docker of this CreateDockerSubmissionRequest.
        :rtype: DockerSubmissionDocker
        """
        return self._docker

    @docker.setter
    def docker(self, docker):
        """Sets the docker of this CreateDockerSubmissionRequest.


        :param docker: The docker of this CreateDockerSubmissionRequest.
        :type docker: DockerSubmissionDocker
        """
        if docker is None:
            raise ValueError("Invalid value for `docker`, must not be `None`")  # noqa: E501

        self._docker = docker
