# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server.openapi import util


class CreateTeamResponse(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, team_id=None):  # noqa: E501
        """CreateTeamResponse - a model defined in OpenAPI

        :param team_id: The team_id of this CreateTeamResponse.  # noqa: E501
        :type team_id: str
        """
        self.openapi_types = {
            'team_id': str
        }

        self.attribute_map = {
            'team_id': 'teamId'
        }

        self._team_id = team_id

    @classmethod
    def from_dict(cls, dikt) -> 'CreateTeamResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The CreateTeamResponse of this CreateTeamResponse.  # noqa: E501
        :rtype: CreateTeamResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def team_id(self):
        """Gets the team_id of this CreateTeamResponse.

        Team ID  # noqa: E501

        :return: The team_id of this CreateTeamResponse.
        :rtype: str
        """
        return self._team_id

    @team_id.setter
    def team_id(self, team_id):
        """Sets the team_id of this CreateTeamResponse.

        Team ID  # noqa: E501

        :param team_id: The team_id of this CreateTeamResponse.
        :type team_id: str
        """

        self._team_id = team_id
