# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server.models.docker_submission_docker import DockerSubmissionDocker
from openapi_server.models.submission_status import SubmissionStatus
from openapi_server import util

from openapi_server.models.docker_submission_docker import DockerSubmissionDocker  # noqa: E501
from openapi_server.models.submission_status import SubmissionStatus  # noqa: E501

class DockerSubmission(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, name=None, submission_id=None, submitter=None, queue_id=None, status=None, docker=None):  # noqa: E501
        """DockerSubmission - a model defined in OpenAPI

        :param name: The name of this DockerSubmission.  # noqa: E501
        :type name: str
        :param submission_id: The submission_id of this DockerSubmission.  # noqa: E501
        :type submission_id: int
        :param submitter: The submitter of this DockerSubmission.  # noqa: E501
        :type submitter: str
        :param queue_id: The queue_id of this DockerSubmission.  # noqa: E501
        :type queue_id: str
        :param status: The status of this DockerSubmission.  # noqa: E501
        :type status: SubmissionStatus
        :param docker: The docker of this DockerSubmission.  # noqa: E501
        :type docker: DockerSubmissionDocker
        """
        self.openapi_types = {
            'name': str,
            'submission_id': int,
            'submitter': str,
            'queue_id': str,
            'status': SubmissionStatus,
            'docker': DockerSubmissionDocker
        }

        self.attribute_map = {
            'name': 'name',
            'submission_id': 'submissionId',
            'submitter': 'submitter',
            'queue_id': 'queueId',
            'status': 'status',
            'docker': 'docker'
        }

        self._name = name
        self._submission_id = submission_id
        self._submitter = submitter
        self._queue_id = queue_id
        self._status = status
        self._docker = docker

    @classmethod
    def from_dict(cls, dikt) -> 'DockerSubmission':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The DockerSubmission of this DockerSubmission.  # noqa: E501
        :rtype: DockerSubmission
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self):
        """Gets the name of this DockerSubmission.

        Name of submission  # noqa: E501

        :return: The name of this DockerSubmission.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this DockerSubmission.

        Name of submission  # noqa: E501

        :param name: The name of this DockerSubmission.
        :type name: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def submission_id(self):
        """Gets the submission_id of this DockerSubmission.

        Submission Id  # noqa: E501

        :return: The submission_id of this DockerSubmission.
        :rtype: int
        """
        return self._submission_id

    @submission_id.setter
    def submission_id(self, submission_id):
        """Sets the submission_id of this DockerSubmission.

        Submission Id  # noqa: E501

        :param submission_id: The submission_id of this DockerSubmission.
        :type submission_id: int
        """

        self._submission_id = submission_id

    @property
    def submitter(self):
        """Gets the submitter of this DockerSubmission.

        Submitter name  # noqa: E501

        :return: The submitter of this DockerSubmission.
        :rtype: str
        """
        return self._submitter

    @submitter.setter
    def submitter(self, submitter):
        """Sets the submitter of this DockerSubmission.

        Submitter name  # noqa: E501

        :param submitter: The submitter of this DockerSubmission.
        :type submitter: str
        """
        if submitter is None:
            raise ValueError("Invalid value for `submitter`, must not be `None`")  # noqa: E501

        self._submitter = submitter

    @property
    def queue_id(self):
        """Gets the queue_id of this DockerSubmission.

        Queue Id  # noqa: E501

        :return: The queue_id of this DockerSubmission.
        :rtype: str
        """
        return self._queue_id

    @queue_id.setter
    def queue_id(self, queue_id):
        """Sets the queue_id of this DockerSubmission.

        Queue Id  # noqa: E501

        :param queue_id: The queue_id of this DockerSubmission.
        :type queue_id: str
        """

        self._queue_id = queue_id

    @property
    def status(self):
        """Gets the status of this DockerSubmission.


        :return: The status of this DockerSubmission.
        :rtype: SubmissionStatus
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this DockerSubmission.


        :param status: The status of this DockerSubmission.
        :type status: SubmissionStatus
        """

        self._status = status

    @property
    def docker(self):
        """Gets the docker of this DockerSubmission.


        :return: The docker of this DockerSubmission.
        :rtype: DockerSubmissionDocker
        """
        return self._docker

    @docker.setter
    def docker(self, docker):
        """Sets the docker of this DockerSubmission.


        :param docker: The docker of this DockerSubmission.
        :type docker: DockerSubmissionDocker
        """
        if docker is None:
            raise ValueError("Invalid value for `docker`, must not be `None`")  # noqa: E501

        self._docker = docker
