# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server.models.docker_submission_docker import DockerSubmissionDocker
from openapi_server import util

from openapi_server.models.docker_submission_docker import DockerSubmissionDocker  # noqa: E501

class DockerSubmission(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, submission_id=None, submitter=None, docker=None):  # noqa: E501
        """DockerSubmission - a model defined in OpenAPI

        :param submission_id: The submission_id of this DockerSubmission.  # noqa: E501
        :type submission_id: int
        :param submitter: The submitter of this DockerSubmission.  # noqa: E501
        :type submitter: str
        :param docker: The docker of this DockerSubmission.  # noqa: E501
        :type docker: DockerSubmissionDocker
        """
        self.openapi_types = {
            'submission_id': int,
            'submitter': str,
            'docker': DockerSubmissionDocker
        }

        self.attribute_map = {
            'submission_id': 'submissionId',
            'submitter': 'submitter',
            'docker': 'docker'
        }

        self._submission_id = submission_id
        self._submitter = submitter
        self._docker = docker

    @classmethod
    def from_dict(cls, dikt) -> 'DockerSubmission':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The DockerSubmission of this DockerSubmission.  # noqa: E501
        :rtype: DockerSubmission
        """
        return util.deserialize_model(dikt, cls)

    @property
    def submission_id(self):
        """Gets the submission_id of this DockerSubmission.

        Queue Id  # noqa: E501

        :return: The submission_id of this DockerSubmission.
        :rtype: int
        """
        return self._submission_id

    @submission_id.setter
    def submission_id(self, submission_id):
        """Sets the submission_id of this DockerSubmission.

        Queue Id  # noqa: E501

        :param submission_id: The submission_id of this DockerSubmission.
        :type submission_id: int
        """

        self._submission_id = submission_id

    @property
    def submitter(self):
        """Gets the submitter of this DockerSubmission.

        Submitter name  # noqa: E501

        :return: The submitter of this DockerSubmission.
        :rtype: str
        """
        return self._submitter

    @submitter.setter
    def submitter(self, submitter):
        """Sets the submitter of this DockerSubmission.

        Submitter name  # noqa: E501

        :param submitter: The submitter of this DockerSubmission.
        :type submitter: str
        """

        self._submitter = submitter

    @property
    def docker(self):
        """Gets the docker of this DockerSubmission.


        :return: The docker of this DockerSubmission.
        :rtype: DockerSubmissionDocker
        """
        return self._docker

    @docker.setter
    def docker(self, docker):
        """Sets the docker of this DockerSubmission.


        :param docker: The docker of this DockerSubmission.
        :type docker: DockerSubmissionDocker
        """

        self._docker = docker
