# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class ListResponseMetadataLinks(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, next=None):  # noqa: E501
        """ListResponseMetadataLinks - a model defined in OpenAPI

        :param next: The next of this ListResponseMetadataLinks.  # noqa: E501
        :type next: str
        """
        self.openapi_types = {
            'next': str
        }

        self.attribute_map = {
            'next': 'next'
        }

        self._next = next

    @classmethod
    def from_dict(cls, dikt) -> 'ListResponseMetadataLinks':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ListResponseMetadata_links of this ListResponseMetadataLinks.  # noqa: E501
        :rtype: ListResponseMetadataLinks
        """
        return util.deserialize_model(dikt, cls)

    @property
    def next(self):
        """Gets the next of this ListResponseMetadataLinks.

        Link to the next page of results  # noqa: E501

        :return: The next of this ListResponseMetadataLinks.
        :rtype: str
        """
        return self._next

    @next.setter
    def next(self, next):
        """Sets the next of this ListResponseMetadataLinks.

        Link to the next page of results  # noqa: E501

        :param next: The next of this ListResponseMetadataLinks.
        :type next: str
        """

        self._next = next
