# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server.models.compute_env import ComputeEnv
from openapi_server.models.list_compute_env_response_all_of import ListComputeEnvResponseAllOf
from openapi_server.models.list_response_metadata import ListResponseMetadata
from openapi_server.models.list_response_metadata_links import ListResponseMetadataLinks
from openapi_server.openapi import util


class ListComputeEnvResponse(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, offset=None, limit=None, links=None, compute_envs=None):  # noqa: E501
        """ListComputeEnvResponse - a model defined in OpenAPI

        :param offset: The offset of this ListComputeEnvResponse.  # noqa: E501
        :type offset: int
        :param limit: The limit of this ListComputeEnvResponse.  # noqa: E501
        :type limit: int
        :param links: The links of this ListComputeEnvResponse.  # noqa: E501
        :type links: ListResponseMetadataLinks
        :param compute_envs: The compute_envs of this ListComputeEnvResponse.  # noqa: E501
        :type compute_envs: List[ComputeEnv]
        """
        self.openapi_types = {
            'offset': int,
            'limit': int,
            'links': ListResponseMetadataLinks,
            'compute_envs': List[ComputeEnv]
        }

        self.attribute_map = {
            'offset': 'offset',
            'limit': 'limit',
            'links': 'links',
            'compute_envs': 'computeEnvs'
        }

        self._offset = offset
        self._limit = limit
        self._links = links
        self._compute_envs = compute_envs

    @classmethod
    def from_dict(cls, dikt) -> 'ListComputeEnvResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ListComputeEnvResponse of this ListComputeEnvResponse.  # noqa: E501
        :rtype: ListComputeEnvResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def offset(self):
        """Gets the offset of this ListComputeEnvResponse.

        Index of the first result that must be returned  # noqa: E501

        :return: The offset of this ListComputeEnvResponse.
        :rtype: int
        """
        return self._offset

    @offset.setter
    def offset(self, offset):
        """Sets the offset of this ListComputeEnvResponse.

        Index of the first result that must be returned  # noqa: E501

        :param offset: The offset of this ListComputeEnvResponse.
        :type offset: int
        """
        if offset is None:
            raise ValueError("Invalid value for `offset`, must not be `None`")  # noqa: E501

        self._offset = offset

    @property
    def limit(self):
        """Gets the limit of this ListComputeEnvResponse.

        Maximum number of results returned  # noqa: E501

        :return: The limit of this ListComputeEnvResponse.
        :rtype: int
        """
        return self._limit

    @limit.setter
    def limit(self, limit):
        """Sets the limit of this ListComputeEnvResponse.

        Maximum number of results returned  # noqa: E501

        :param limit: The limit of this ListComputeEnvResponse.
        :type limit: int
        """
        if limit is None:
            raise ValueError("Invalid value for `limit`, must not be `None`")  # noqa: E501

        self._limit = limit

    @property
    def links(self):
        """Gets the links of this ListComputeEnvResponse.


        :return: The links of this ListComputeEnvResponse.
        :rtype: ListResponseMetadataLinks
        """
        return self._links

    @links.setter
    def links(self, links):
        """Sets the links of this ListComputeEnvResponse.


        :param links: The links of this ListComputeEnvResponse.
        :type links: ListResponseMetadataLinks
        """
        if links is None:
            raise ValueError("Invalid value for `links`, must not be `None`")  # noqa: E501

        self._links = links

    @property
    def compute_envs(self):
        """Gets the compute_envs of this ListComputeEnvResponse.

        An array of queues  # noqa: E501

        :return: The compute_envs of this ListComputeEnvResponse.
        :rtype: List[ComputeEnv]
        """
        return self._compute_envs

    @compute_envs.setter
    def compute_envs(self, compute_envs):
        """Sets the compute_envs of this ListComputeEnvResponse.

        An array of queues  # noqa: E501

        :param compute_envs: The compute_envs of this ListComputeEnvResponse.
        :type compute_envs: List[ComputeEnv]
        """

        self._compute_envs = compute_envs
