# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server.models.submission import Submission
from openapi_server import util

from openapi_server.models.submission import Submission  # noqa: E501

class ListSubmissionResponseAllOf(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, submissions=None):  # noqa: E501
        """ListSubmissionResponseAllOf - a model defined in OpenAPI

        :param submissions: The submissions of this ListSubmissionResponseAllOf.  # noqa: E501
        :type submissions: List[Submission]
        """
        self.openapi_types = {
            'submissions': List[Submission]
        }

        self.attribute_map = {
            'submissions': 'submissions'
        }

        self._submissions = submissions

    @classmethod
    def from_dict(cls, dikt) -> 'ListSubmissionResponseAllOf':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ListSubmissionResponse_allOf of this ListSubmissionResponseAllOf.  # noqa: E501
        :rtype: ListSubmissionResponseAllOf
        """
        return util.deserialize_model(dikt, cls)

    @property
    def submissions(self):
        """Gets the submissions of this ListSubmissionResponseAllOf.

        An array of queues  # noqa: E501

        :return: The submissions of this ListSubmissionResponseAllOf.
        :rtype: List[Submission]
        """
        return self._submissions

    @submissions.setter
    def submissions(self, submissions):
        """Sets the submissions of this ListSubmissionResponseAllOf.

        An array of queues  # noqa: E501

        :param submissions: The submissions of this ListSubmissionResponseAllOf.
        :type submissions: List[Submission]
        """

        self._submissions = submissions
