# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class WorkflowSubmission(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, submission_id=None, submitter=None, workflow=None, workflow_inputs=None):  # noqa: E501
        """WorkflowSubmission - a model defined in OpenAPI

        :param submission_id: The submission_id of this WorkflowSubmission.  # noqa: E501
        :type submission_id: int
        :param submitter: The submitter of this WorkflowSubmission.  # noqa: E501
        :type submitter: str
        :param workflow: The workflow of this WorkflowSubmission.  # noqa: E501
        :type workflow: str
        :param workflow_inputs: The workflow_inputs of this WorkflowSubmission.  # noqa: E501
        :type workflow_inputs: str
        """
        self.openapi_types = {
            'submission_id': int,
            'submitter': str,
            'workflow': str,
            'workflow_inputs': str
        }

        self.attribute_map = {
            'submission_id': 'submissionId',
            'submitter': 'submitter',
            'workflow': 'workflow',
            'workflow_inputs': 'workflowInputs'
        }

        self._submission_id = submission_id
        self._submitter = submitter
        self._workflow = workflow
        self._workflow_inputs = workflow_inputs

    @classmethod
    def from_dict(cls, dikt) -> 'WorkflowSubmission':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The WorkflowSubmission of this WorkflowSubmission.  # noqa: E501
        :rtype: WorkflowSubmission
        """
        return util.deserialize_model(dikt, cls)

    @property
    def submission_id(self):
        """Gets the submission_id of this WorkflowSubmission.

        Queue Id  # noqa: E501

        :return: The submission_id of this WorkflowSubmission.
        :rtype: int
        """
        return self._submission_id

    @submission_id.setter
    def submission_id(self, submission_id):
        """Sets the submission_id of this WorkflowSubmission.

        Queue Id  # noqa: E501

        :param submission_id: The submission_id of this WorkflowSubmission.
        :type submission_id: int
        """

        self._submission_id = submission_id

    @property
    def submitter(self):
        """Gets the submitter of this WorkflowSubmission.

        Submitter name  # noqa: E501

        :return: The submitter of this WorkflowSubmission.
        :rtype: str
        """
        return self._submitter

    @submitter.setter
    def submitter(self, submitter):
        """Sets the submitter of this WorkflowSubmission.

        Submitter name  # noqa: E501

        :param submitter: The submitter of this WorkflowSubmission.
        :type submitter: str
        """

        self._submitter = submitter

    @property
    def workflow(self):
        """Gets the workflow of this WorkflowSubmission.

        Workflow to run  # noqa: E501

        :return: The workflow of this WorkflowSubmission.
        :rtype: str
        """
        return self._workflow

    @workflow.setter
    def workflow(self, workflow):
        """Sets the workflow of this WorkflowSubmission.

        Workflow to run  # noqa: E501

        :param workflow: The workflow of this WorkflowSubmission.
        :type workflow: str
        """

        self._workflow = workflow

    @property
    def workflow_inputs(self):
        """Gets the workflow_inputs of this WorkflowSubmission.

        Worklfow inputs  # noqa: E501

        :return: The workflow_inputs of this WorkflowSubmission.
        :rtype: str
        """
        return self._workflow_inputs

    @workflow_inputs.setter
    def workflow_inputs(self, workflow_inputs):
        """Sets the workflow_inputs of this WorkflowSubmission.

        Worklfow inputs  # noqa: E501

        :param workflow_inputs: The workflow_inputs of this WorkflowSubmission.
        :type workflow_inputs: str
        """

        self._workflow_inputs = workflow_inputs
