# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server.models.submission_status import SubmissionStatus
from openapi_server.openapi import util


class WorkflowSubmission(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, name=None, id=None, submitter=None, queue_id=None, status=None, workflow=None, workflow_inputs=None):  # noqa: E501
        """WorkflowSubmission - a model defined in OpenAPI

        :param name: The name of this WorkflowSubmission.  # noqa: E501
        :type name: str
        :param id: The id of this WorkflowSubmission.  # noqa: E501
        :type id: int
        :param submitter: The submitter of this WorkflowSubmission.  # noqa: E501
        :type submitter: str
        :param queue_id: The queue_id of this WorkflowSubmission.  # noqa: E501
        :type queue_id: str
        :param status: The status of this WorkflowSubmission.  # noqa: E501
        :type status: SubmissionStatus
        :param workflow: The workflow of this WorkflowSubmission.  # noqa: E501
        :type workflow: str
        :param workflow_inputs: The workflow_inputs of this WorkflowSubmission.  # noqa: E501
        :type workflow_inputs: str
        """
        self.openapi_types = {
            'name': str,
            'id': int,
            'submitter': str,
            'queue_id': str,
            'status': SubmissionStatus,
            'workflow': str,
            'workflow_inputs': str
        }

        self.attribute_map = {
            'name': 'name',
            'id': 'id',
            'submitter': 'submitter',
            'queue_id': 'queueId',
            'status': 'status',
            'workflow': 'workflow',
            'workflow_inputs': 'workflowInputs'
        }

        self._name = name
        self._id = id
        self._submitter = submitter
        self._queue_id = queue_id
        self._status = status
        self._workflow = workflow
        self._workflow_inputs = workflow_inputs

    @classmethod
    def from_dict(cls, dikt) -> 'WorkflowSubmission':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The WorkflowSubmission of this WorkflowSubmission.  # noqa: E501
        :rtype: WorkflowSubmission
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self):
        """Gets the name of this WorkflowSubmission.

        Name of submission  # noqa: E501

        :return: The name of this WorkflowSubmission.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this WorkflowSubmission.

        Name of submission  # noqa: E501

        :param name: The name of this WorkflowSubmission.
        :type name: str
        """

        self._name = name

    @property
    def id(self):
        """Gets the id of this WorkflowSubmission.

        Submission Id  # noqa: E501

        :return: The id of this WorkflowSubmission.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this WorkflowSubmission.

        Submission Id  # noqa: E501

        :param id: The id of this WorkflowSubmission.
        :type id: int
        """

        self._id = id

    @property
    def submitter(self):
        """Gets the submitter of this WorkflowSubmission.

        Submitter name  # noqa: E501

        :return: The submitter of this WorkflowSubmission.
        :rtype: str
        """
        return self._submitter

    @submitter.setter
    def submitter(self, submitter):
        """Sets the submitter of this WorkflowSubmission.

        Submitter name  # noqa: E501

        :param submitter: The submitter of this WorkflowSubmission.
        :type submitter: str
        """

        self._submitter = submitter

    @property
    def queue_id(self):
        """Gets the queue_id of this WorkflowSubmission.

        Queue Id  # noqa: E501

        :return: The queue_id of this WorkflowSubmission.
        :rtype: str
        """
        return self._queue_id

    @queue_id.setter
    def queue_id(self, queue_id):
        """Sets the queue_id of this WorkflowSubmission.

        Queue Id  # noqa: E501

        :param queue_id: The queue_id of this WorkflowSubmission.
        :type queue_id: str
        """

        self._queue_id = queue_id

    @property
    def status(self):
        """Gets the status of this WorkflowSubmission.


        :return: The status of this WorkflowSubmission.
        :rtype: SubmissionStatus
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this WorkflowSubmission.


        :param status: The status of this WorkflowSubmission.
        :type status: SubmissionStatus
        """

        self._status = status

    @property
    def workflow(self):
        """Gets the workflow of this WorkflowSubmission.

        Workflow to run  # noqa: E501

        :return: The workflow of this WorkflowSubmission.
        :rtype: str
        """
        return self._workflow

    @workflow.setter
    def workflow(self, workflow):
        """Sets the workflow of this WorkflowSubmission.

        Workflow to run  # noqa: E501

        :param workflow: The workflow of this WorkflowSubmission.
        :type workflow: str
        """

        self._workflow = workflow

    @property
    def workflow_inputs(self):
        """Gets the workflow_inputs of this WorkflowSubmission.

        Worklfow inputs  # noqa: E501

        :return: The workflow_inputs of this WorkflowSubmission.
        :rtype: str
        """
        return self._workflow_inputs

    @workflow_inputs.setter
    def workflow_inputs(self, workflow_inputs):
        """Sets the workflow_inputs of this WorkflowSubmission.

        Worklfow inputs  # noqa: E501

        :param workflow_inputs: The workflow_inputs of this WorkflowSubmission.
        :type workflow_inputs: str
        """

        self._workflow_inputs = workflow_inputs
